defaults:
  - local_system   : ${oc.env:CMB_ML_LOCAL_SYSTEM}
  - file_system    : common_fs
  - pipeline       : assembly_sim
  - scenario       : scenario_t
  - splits         : "1-10"
  # simulation must listed be after scenario and splits to build the simulation seed
  - model/sim      : sim_t
  - model/analysis : basic_analysis
  - override hydra/job_logging: custom_log
  - _self_

dataset_name: ${scenario.map_fields}_${scenario.nside}_${splits.name}
working_dir : "Simulation_Working/"
hydra:
  run:
    dir: Logs/${now:%Y-%m-%d-%H-%M-%S}
  verbose: true

# Settings below this point are used for interpolation.
# These are not to be used directly in the python
# They are picked up from here and MAY be used elsewhere in the yamls.
# In the scenario yaml
nside          : 128
detectors      : [44, 70, 100, 143, 217, 353]  #, 545, 857]
map_fields     : "I"

# In the simulation yaml (only relevant to the simulation portion of the pipeline)
nside_sky      : 256
preset_strings : ["d9", "s4", "f1", "a1", "co1", "cib1", "ksz1", "tsz1", "rg1"]

# In the splits yaml
n_test_cap: null
