# For maps
px_functions: &stat_funcs
  mse:
    plot_name: "Mean Squared Error (MSE)"
    axis_name: "MSE"
    label: MSE
    func: "skimage.metrics.mean_squared_error"
  psnr:
    plot_name: "Peak Signal-to-Noise Ratio (PNSR)"
    axis_name: "PNSR"
    label: PSNR
    func: "psnr"
  rmse:
    plot_name: "Root Mean Squared Error (RMSE)"
    axis_name: "RMSE"
    label: RMSE
    func: "rmse"
  mae:
    plot_name: "Mean Absolute Error (MAE)"
    axis_name: "MAE"
    label: MAE
    func: "sklearn.metrics.mean_absolute_error"
  r2:
    plot_name: "Coefficient of Determination (R^2)"
    axis_name: "R2"
    label: R2
    func: "sklearn.metrics.r2_score"
  nrmse:
    plot_name: "Normalized Root MSE (NRMSE)"
    axis_name: "NRMSE"
    label: NRMSE
    func: "skimage.metrics.normalized_root_mse"
    kwargs: {normalization: "euclidean"}
px_operations:
  num_processes: 10

# For power spectra
mask_threshold:  0.9  # Per Planck's 2015 results:IX. Diffuse component separation: CMB maps

mask_sm_apo_size:  20.6  # Matching smallest beam and pyilc perform_ILC_at_beam
mask_sm_apo_type:  'C1'  # NaMaster mask type

post_map_mask_b4_deconv : false       # Whether the post_map will be masked before deconvolving it
post_map_do_deconv: false             # Whether the post_map will be deconvolved
post_map_mask_b4_remove_dipole: true  # Whether the post_map will be masked before removing the dipole
post_map_remove_dipole: true          # Whether the post_map will have the dipole removed

ps_use_smooth_mask: true  # Whether to use the smoothed mask for power spectrum calculations

lmax_ratio: 2.0
beam_real:
  _target_: cmbml.utils.physics_beam.NoBeam
  _partial_: true  # _partial_ is a flag for Hydra. In this case, 
                   #    lmax will come from python code

beam_cmbnncs:
  _target_: cmbml.utils.physics_beam.NoBeam
  _partial_: true  # _partial_ is a flag for Hydra. In this case, 
                   #    lmax will come from python code

beam_pyilc:
  _target_: cmbml.utils.physics_beam.GaussianBeam
  _partial_: true  # _partial_ is a flag for Hydra. In this case, 
                   #    lmax will come from python code
  beam_fwhm: 20.6

ps_functions: *stat_funcs
ps_operations:
  num_processes: 10
